/**
 * POST /api/energeia/daemon/register — register a local daemon auth token
 *
 * Called once by the install.command script on first setup.
 * Protected by CF Access JWT — only Cam can register a daemon token.
 *
 * Body: { token, mac_id }
 *   token  — UUID generated by the install script
 *   mac_id — hostname or hardware UUID for identification
 *
 * Env: CF_ACCESS_AUD, ENERGEIA_ACTIONS
 */

export async function onRequestPost(ctx) {
  const { env, request } = ctx;

  const authErr = await validateCFAccess(request, env.CF_ACCESS_AUD);
  if (authErr) return jsonResponse({ error: 'Unauthorized', detail: authErr }, 401);

  let body;
  try { body = await request.json(); }
  catch (_) { return jsonResponse({ error: 'Invalid JSON body' }, 400); }

  const { token, mac_id = 'unknown' } = body;

  if (!token || !/^[0-9a-f-]{36}$/.test(token)) {
    return jsonResponse({ error: 'token must be a valid UUID v4' }, 400);
  }

  if (!env.ENERGEIA_ACTIONS) {
    return jsonResponse({ ok: true, note: 'KV not configured — token not persisted (dev mode)' }, 201);
  }

  await env.ENERGEIA_ACTIONS.put(
    `daemon-token:${token}`,
    JSON.stringify({ registered: new Date().toISOString(), mac_id }),
    { expirationTtl: 60 * 60 * 24 * 365 * 2 } /* 2-year TTL */
  );

  return jsonResponse({ ok: true, mac_id, message: 'Daemon token registered.' }, 201);
}

function jsonResponse(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status, headers: { 'Content-Type': 'application/json; charset=utf-8' }
  });
}

async function validateCFAccess(request, audience) {
  if (!audience) return null;
  const token = request.headers.get('CF-Access-Jwt-Assertion');
  if (!token) return 'Missing CF-Access-Jwt-Assertion header';
  try {
    const [headerB64] = token.split('.');
    const header = JSON.parse(atob(headerB64.replace(/-/g, '+').replace(/_/g, '/')));
    const certsResp = await fetch('https://skeptou.cloudflareaccess.com/cdn-cgi/access/certs');
    if (!certsResp.ok) return 'Failed to fetch Access certs';
    const certs = await certsResp.json();
    const jwk = (certs.keys || []).find(k => k.kid === header.kid);
    if (!jwk) return 'No matching JWK';
    const key = await crypto.subtle.importKey('jwk', jwk, { name: 'RSASSA-PKCS1-v1_5', hash: 'SHA-256' }, false, ['verify']);
    const [, payloadB64, sigB64] = token.split('.');
    const sig  = Uint8Array.from(atob(sigB64.replace(/-/g, '+').replace(/_/g, '/')), c => c.charCodeAt(0));
    const data = new TextEncoder().encode(`${headerB64}.${payloadB64}`);
    const valid = await crypto.subtle.verify('RSASSA-PKCS1-v1_5', key, sig, data);
    if (!valid) return 'Invalid JWT signature';
    const payload = JSON.parse(atob(payloadB64.replace(/-/g, '+').replace(/_/g, '/')));
    const audOk = Array.isArray(payload.aud) ? payload.aud.includes(audience) : payload.aud === audience;
    if (!audOk) return 'JWT audience mismatch';
    if (payload.exp && payload.exp < Math.floor(Date.now() / 1000)) return 'JWT expired';
    return null;
  } catch (e) {
    return `JWT validation error: ${e.message}`;
  }
}
