/**
 * POST /api/energeia/daemon/register — register a local daemon auth token
 *
 * Called once from the energeia Settings UI after daemon install.
 * CF Access protects the entire energeia.skeptou.com domain, so only
 * authenticated users can reach this endpoint at all. No additional
 * JWT validation is needed here — the CF Access gate is the auth layer.
 * Security model: the UUID token itself is the secret; only the person
 * who ran install.command knows it.
 *
 * Body: { token, mac_id }
 *   token  — UUID generated by the install script
 *   mac_id — hostname or hardware UUID for identification
 *
 * Env: ENERGEIA_ACTIONS
 */

export async function onRequestPost(ctx) {
  const { env, request } = ctx;

  let body;
  try { body = await request.json(); }
  catch (_) { return jsonResponse({ error: 'Invalid JSON body' }, 400); }

  const { token, mac_id = 'unknown' } = body;

  if (!token || !/^[0-9a-f-]{36}$/.test(token)) {
    return jsonResponse({ error: 'token must be a valid UUID v4' }, 400);
  }

  if (!env.ENERGEIA_ACTIONS) {
    return jsonResponse({ ok: true, note: 'KV not configured — token not persisted (dev mode)' }, 201);
  }

  await env.ENERGEIA_ACTIONS.put(
    `daemon-token:${token}`,
    JSON.stringify({ registered: new Date().toISOString(), mac_id }),
    { expirationTtl: 60 * 60 * 24 * 365 * 2 } /* 2-year TTL */
  );

  return jsonResponse({ ok: true, mac_id, message: 'Daemon token registered.' }, 201);
}

function jsonResponse(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status, headers: { 'Content-Type': 'application/json; charset=utf-8' }
  });
}
